### ISSUE TITLE
Orion CLI does not get input from Windows command line

### ISSUE THREAD

**Issue by mrauhu** [matteodem/orion-cli#17]
Same bug:

* https://github.com/matteodem/orion-cli/issues/13
* https://github.com/matteodem/meteor-boilerplate/issues/83

## OS and software

```batch

C:\dev>ver

Microsoft Windows [Version 6.1.7601]

C:\dev>node -v
v0.10.38

C:\dev>npm -v
1.4.28

C:\dev>meteor --version
Meteor 1.1.0.2
```

## How to reproduce

1\. Create project

```batch
orion create test
cd test
```

2\. Try to generate view
```
C:\dev\test>orion generate view          _
orion | What's the name of your view? |
```
_ — cursor position, on same line where command entered

Let's name it `test_view`

### Result

```
fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\dev\test\undefined\private\templates\html\view.html'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at %APPDATA%\npm\node_modules\orion-cli\lib\fileManager.js:20:32
    at Array.forEach (native)
    at Object.FileManager.generateTemplates (%APPDATA%\npm\node_modules\orion-cli\lib\fileManager.js:19:16)
    at %APPDATA%\npm\node_modules\orion-cli\commands\generate.js:88:29
    at %APPDATA%\npm\node_modules\orion-cli\node_modules\prompt\lib\prompt.js:316:32
    at %APPDATA%\npm\node_modules\orion-cli\node_modules\prompt\node_modules\utile\node_modules\async\lib\async.js:142:25
    at assembler (%APPDATA%\npm\node_modules\orion-cli\node_modules\prompt\lib\prompt.js:313:9)
    at %APPDATA%\npm\node_modules\orion-cli\node_modules\prompt\lib\prompt.js:322:32
```

###  Expected

```
Successfully created following files:
    client/views/test_view/test_view.html
    client/views/test_view/test_view.js
```

**Comment by mrauhu** [comment]
Fix already added https://github.com/matteodem/orion-cli/commit/bc710ef103e7faec93516176a8ec4396c54bffff, but NPM version not changed.
